
class KeyManager {
    #private_key
    #public_key
    #ed

    constructor (seed) {
        throw new Error("javascript KeyManager is not implemented yet")
        // as per the rust implementation, private_key is just the seed
        this.#private_key = seed
    
        // TODO: update this repo to use ESM then we won't have to do this, or the associated ugliness below

        import("@noble/ed25519").then(ed => {
            import("@noble/hashes/sha512")
            .then(({ sha512 }) => {
                ed.etc.sha512Sync = (...m) => sha512(ed.etc.concatBytes(...m));
                this.#ed = ed
                this.#public_key = ed.getPublicKey(this.#private_key)    
            })
        })
    }

    publicKey () {
        if(!this.#public_key) {
            throw new Error ("Attempt to access pubkey before initialized")
        }
        return this.#public_key
    }

    sign (message) {
        // const encoder = new TextEncoder();


        const message_bytes = stringToByteArray(message)

        if(!this.#ed) {
            throw new Error ("Attempt to use ed before initialized")
        }

        return this.#ed.sign(message_bytes, this.#private_key)
    }

    verify (message, signature) {
        return KeyManager.verifyWithPublicKey(message, signature, this.publicKey())
    }
    /**
     * Returns true if the signature was generated by signing the message using the keypair of the pubkey
     *
     * @param {string} message - The first number.
     * @param {Uint8Array} signature - The second number.
     * @param {Uint8Array} pubkey - The second number.
     * @returns {bool} The sum of the two numbers.
     */
    static async verifyWithPublicKey (message, signature, pubkey) {
        const message_bytes = stringToByteArray(message)

        const ed = await import("@noble/ed25519")

        return ed.verify(signature, message_bytes, pubkey)
    }
}

function stringToByteArray(str) {
    const byteArray = [];
    for (let i = 0; i < str.length; i++) {
      byteArray.push(str.charCodeAt(i));
    }
    return new Uint8Array(byteArray);
  }

module.exports = KeyManager
